general {
    lock_cmd = sh /home/boing/Dotfiles/quickshell/scripts/lock.sh       # command to run when locking
    before_sleep_cmd = sh /home/boing/Dotfiles/quickshell/scripts/lock.sh # lock before sleep
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display
}

listener {
    timeout = 300                       # 5 minutes
    on-timeout = sh /home/boing/Dotfiles/quickshell/scripts/lock.sh     # lock screen when timeout has passed
}

listener {
    timeout = 330                       # 5.5 minutes
    on-timeout = hyprctl dispatch dpms off # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on   # screen on when activity is detected after timeout has fired
}
