pragma Singleton
import QtQuick

QtObject {
    property string background: "#ff101416"
    property string error: "#ffffb4ab"
    property string error_container: "#ff93000a"
    property string inverse_on_surface: "#ff2d3133"
    property string inverse_primary: "#ff006684"
    property string inverse_surface: "#ffe0e3e5"
    property string on_background: "#ffe0e3e5"
    property string on_error: "#ff690005"
    property string on_error_container: "#ffffdad6"
    property string on_primary: "#ff003546"
    property string on_primary_container: "#ff00394b"
    property string on_primary_fixed: "#ff001f2a"
    property string on_primary_fixed_variant: "#ff004d64"
    property string on_secondary: "#ff173440"
    property string on_secondary_container: "#ffc7e4f4"
    property string on_secondary_fixed: "#ff001f2a"
    property string on_secondary_fixed_variant: "#ff2f4a57"
    property string on_surface: "#ffe0e3e5"
    property string on_surface_variant: "#ffbfc8ce"
    property string on_tertiary: "#ff452058"
    property string on_tertiary_container: "#ff48235c"
    property string on_tertiary_fixed: "#ff2e0742"
    property string on_tertiary_fixed_variant: "#ff5d3770"
    property string outline: "#ff899298"
    property string outline_variant: "#ff3f484d"
    property string primary: "#ffb4e6ff"
    property string primary_container: "#ff7fcdf0"
    property string primary_fixed: "#ffbde9ff"
    property string primary_fixed_dim: "#ff83d1f4"
    property string scrim: "#ff000000"
    property string secondary: "#ffaecbda"
    property string secondary_container: "#ff2f4a57"
    property string secondary_fixed: "#ffcae7f7"
    property string secondary_fixed_dim: "#ffaecbda"
    property string shadow: "#ff000000"
    property string source_color: "#ff7fcdf0"
    property string surface: "#ff101416"
    property string surface_bright: "#ff363a3c"
    property string surface_container: "#ff1c2022"
    property string surface_container_high: "#ff272a2d"
    property string surface_container_highest: "#ff313538"
    property string surface_container_low: "#ff181c1e"
    property string surface_container_lowest: "#ff0b0f11"
    property string surface_dim: "#ff101416"
    property string surface_tint: "#ff83d1f4"
    property string surface_variant: "#ff3f484d"
    property string tertiary: "#fff4d4ff"
    property string tertiary_container: "#ffe1b2f5"
    property string tertiary_fixed: "#fff6d9ff"
    property string tertiary_fixed_dim: "#ffe5b5f9"
}
