-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#131313",
  base01 = "#0e0e0e",
  base02 = "#1b1b1b",
  base03 = "#474747",
  base04 = "#c6c6c6",
  base05 = "#e2e2e2",
  base06 = "#303030",
  base07 = "#393939",

  base08 = "#d5d5d5",
  base09 = "#e2e2e2",
  base0A = "#c6c6c6",
  base0B = "#ffffff",
  base0C = "#919191",
  base0D = "#d4d4d4",
  base0E = "#474747",
  base0F = "#adadad",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#d4d4d4',
  fg = '#000000', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#bcbcbc',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#919191',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e2e2e2',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c6c6c6',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#5e5e5e',
})