-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#101417",
  base01 = "#0a0f12",
  base02 = "#181c20",
  base03 = "#41484d",
  base04 = "#c1c7ce",
  base05 = "#dfe3e8",
  base06 = "#2d3135",
  base07 = "#353a3e",

  base08 = "#bfade1",
  base09 = "#cec0e8",
  base0A = "#b7c9d8",
  base0B = "#94cdf7",
  base0C = "#4b4163",
  base0D = "#004c6d",
  base0E = "#384956",
  base0F = "#96b0c6",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#004c6d',
  fg = '#c8e6ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#a288d4',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8b9198',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#cec0e8',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b7c9d8',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#246488',
})