-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#15130c",
  base01 = "#100e07",
  base02 = "#1d1c13",
  base03 = "#4a4739",
  base04 = "#ccc6b5",
  base05 = "#e8e2d5",
  base06 = "#333027",
  base07 = "#3b3930",

  base08 = "#96c7a8",
  base09 = "#a7d0b6",
  base0A = "#cfc7a2",
  base0B = "#d6c871",
  base0C = "#294e3b",
  base0D = "#504700",
  base0E = "#4c472b",
  base0F = "#beb380",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#504700',
  fg = '#f3e489', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#75b58d',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#959181',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a7d0b6',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#cfc7a2',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#695f11',
})