[color]
background = 'light'
foreground = '#000000'

; gradient = 0
gradient = 1
gradient_color_1 = '#3b3b3b'
gradient_color_2 = '#000000'
gradient_color_3 = '#ffffff'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#3b3b3b'
horizontal_gradient_color_2 = '#000000'
horizontal_gradient_color_3 = '#ffffff'
horizontal_gradient_color_4 = '#000000'
horizontal_gradient_color_5 = '#3b3b3b'


