[color]
background = 'light'
foreground = '#8c4e28'

; gradient = 0
gradient = 1
gradient_color_1 = '#ffdbc9'
gradient_color_2 = '#8c4e28'
gradient_color_3 = '#331200'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#ffdbc9'
horizontal_gradient_color_2 = '#8c4e28'
horizontal_gradient_color_3 = '#331200'
horizontal_gradient_color_4 = '#8c4e28'
horizontal_gradient_color_5 = '#ffdbc9'


