[color]
background = 'light'
foreground = '#695f11'

; gradient = 0
gradient = 1
gradient_color_1 = '#f3e489'
gradient_color_2 = '#695f11'
gradient_color_3 = '#201c00'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#f3e489'
horizontal_gradient_color_2 = '#695f11'
horizontal_gradient_color_3 = '#201c00'
horizontal_gradient_color_4 = '#695f11'
horizontal_gradient_color_5 = '#f3e489'


