-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#fff8f6",
  base01 = "#ffffff",
  base02 = "#fff1eb",
  base03 = "#d7c2b9",
  base04 = "#52443c",
  base05 = "#221a15",
  base06 = "#ffede5",
  base07 = "#fff8f6",

  base08 = "#525029",
  base09 = "#636032",
  base0A = "#765848",
  base0B = "#8c4e28",
  base0C = "#eae5ab",
  base0D = "#ffdbc9",
  base0E = "#ffdbc9",
  base0F = "#564035",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#ffdbc9',
  fg = '#331200', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#302f18',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#85746b',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#636032',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#765848',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#ffb68e',
})