-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#f9f9f9",
  base01 = "#ffffff",
  base02 = "#f3f3f3",
  base03 = "#c6c6c6",
  base04 = "#474747",
  base05 = "#1b1b1b",
  base06 = "#f1f1f1",
  base07 = "#f9f9f9",

  base08 = "#2e2e2e",
  base09 = "#3b3b3b",
  base0A = "#5e5e5e",
  base0B = "#000000",
  base0C = "#747474",
  base0D = "#3b3b3b",
  base0E = "#e2e2e2",
  base0F = "#454545",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#3b3b3b',
  fg = '#ffffff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#151515',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#777777',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#3b3b3b',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#5e5e5e',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#c6c6c6',
})