-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#f6f9fe",
  base01 = "#ffffff",
  base02 = "#f1f4f9",
  base03 = "#c1c7ce",
  base04 = "#41484d",
  base05 = "#181c20",
  base06 = "#eef1f6",
  base07 = "#f6f9fe",

  base08 = "#574e6d",
  base09 = "#63597c",
  base0A = "#4f606e",
  base0B = "#246488",
  base0C = "#e9ddff",
  base0D = "#c8e6ff",
  base0E = "#d3e5f5",
  base0F = "#3a4650",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#c8e6ff',
  fg = '#001e2e', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#3f394f',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#71787e',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#63597c',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#4f606e',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#94cdf7',
})